backend = "glx";
# Enable fading on windows
fading = true;
fade-delta = 8;

# Enable animations when windows appear
wintype-fading = true;
wintype-fading-exclude = "class_g = 'I3bar'";

# Animation for fading windows (0.1 to 1)
frame-opacity = 0.95;

# Set animation time for fade-in and fade-out
fade-in-step = 0.075;
fade-out-step = 0.075;

# Enable shadow for windows
opacity-rule = [
    "99:class_g = 'I3bar' && focused = 0",
    "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];
active-opacity = 0.95;
inactive-opacity = 0.8;
# shadow = true;
# shadow-radius = 15;
shadow-opacity = 0.8;
